//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompleteSchoolManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolModelContainer : DbContext
    {
        public SchoolModelContainer()
            : base("name=SchoolModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student> StudentSet { get; set; }
        public virtual DbSet<Courses> CoursesSet { get; set; }
        public virtual DbSet<Material> MaterialSet { get; set; }
        public virtual DbSet<Teacher> TeacherSet { get; set; }
    }
}
